/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dash.java
 *
 * Created on Jun 26, 2013, 2:17:59 PM
 */

package gui.dashboard_ui;

/**
 *
 * @author rickster
 */
public class Dash extends javax.swing.JFrame {

    /** Creates new form Dash */
    public Dash() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        delete_action_button = new javax.swing.JButton();
        action_list_combo = new javax.swing.JComboBox();
        add_action_button = new javax.swing.JButton();
        insert_action_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        connection_type_combo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        use_proxies_checkbox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        dashboard_tabbed_pane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        actions_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        log_textarea = new javax.swing.JTextArea();
        version_label = new javax.swing.JLabel();
        run_test_button = new javax.swing.JButton();
        stop_test_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        load_test_menu_item = new javax.swing.JMenuItem();
        save_test_menu_item = new javax.swing.JMenuItem();
        tool_menu = new javax.swing.JMenu();
        inspector_menu_item = new javax.swing.JMenuItem();
        show_info_window_menu_item = new javax.swing.JMenuItem();
        reboot_menu_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Italian JOB");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        delete_action_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete_action_button.setText("Delete Action");

        action_list_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        add_action_button.setFont(new java.awt.Font("Tahoma", 0, 14));
        add_action_button.setText("Add Action");
        add_action_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_action_buttonActionPerformed(evt);
            }
        });

        insert_action_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_action_button.setText("Insert Action");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(action_list_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(add_action_button)
                .addGap(15, 15, 15)
                .addComponent(insert_action_button)
                .addGap(18, 18, 18)
                .addComponent(delete_action_button)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(action_list_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_action_button)
                    .addComponent(delete_action_button)
                    .addComponent(insert_action_button))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Default Connection Options");

        connection_type_combo.setFont(new java.awt.Font("Tahoma", 0, 14));
        connection_type_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Phantomjs", "IE", "Firefox", "Chrome", "Socket" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Connection Type");

        use_proxies_checkbox.setFont(new java.awt.Font("Tahoma", 0, 14));
        use_proxies_checkbox.setSelected(true);
        use_proxies_checkbox.setText("Use Proxies");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(use_proxies_checkbox)
                            .addComponent(connection_type_combo, 0, 111, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connection_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(use_proxies_checkbox)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Profile:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        actions_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        actions_table.setFont(new java.awt.Font("Tahoma", 0, 18));
        actions_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(actions_table);

        dashboard_tabbed_pane.addTab("Actions", jScrollPane1);

        log_textarea.setBackground(new java.awt.Color(0, 0, 0));
        log_textarea.setColumns(20);
        log_textarea.setEditable(false);
        log_textarea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        log_textarea.setForeground(new java.awt.Color(0, 255, 0));
        log_textarea.setLineWrap(true);
        log_textarea.setRows(5);
        log_textarea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(log_textarea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboard_tabbed_pane.addTab("Log", jPanel4);

        version_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        version_label.setForeground(new java.awt.Color(0, 0, 204));
        version_label.setText("Version:");

        run_test_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        run_test_button.setText("Run Test");

        stop_test_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stop_test_button.setText("Stop Test");

        jMenu1.setText("File");

        load_test_menu_item.setText("Load Test");
        jMenu1.add(load_test_menu_item);

        save_test_menu_item.setText("Save Test");
        jMenu1.add(save_test_menu_item);

        jMenuBar1.add(jMenu1);

        tool_menu.setText("Tools");

        inspector_menu_item.setText("Inspector");
        tool_menu.add(inspector_menu_item);

        show_info_window_menu_item.setText("Trainer Info Window");
        tool_menu.add(show_info_window_menu_item);

        reboot_menu_item.setText("Reboot Trainer");
        tool_menu.add(reboot_menu_item);

        jMenuBar1.add(tool_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard_tabbed_pane, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(run_test_button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop_test_button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(489, 489, 489)
                        .addComponent(version_label, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(version_label)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(run_test_button)
                            .addComponent(stop_test_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(dashboard_tabbed_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_action_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_action_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_action_buttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox action_list_combo;
    private javax.swing.JTable actions_table;
    private javax.swing.JButton add_action_button;
    private javax.swing.JComboBox connection_type_combo;
    private javax.swing.JTabbedPane dashboard_tabbed_pane;
    private javax.swing.JButton delete_action_button;
    private javax.swing.JButton insert_action_button;
    private javax.swing.JMenuItem inspector_menu_item;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem load_test_menu_item;
    private javax.swing.JTextArea log_textarea;
    private javax.swing.JMenuItem reboot_menu_item;
    private javax.swing.JButton run_test_button;
    private javax.swing.JMenuItem save_test_menu_item;
    private javax.swing.JMenuItem show_info_window_menu_item;
    private javax.swing.JButton stop_test_button;
    private javax.swing.JMenu tool_menu;
    private javax.swing.JCheckBox use_proxies_checkbox;
    private javax.swing.JLabel version_label;
    // End of variables declaration//GEN-END:variables

}
