/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActionData.java
 *
 * Created on Jun 29, 2013, 1:06:55 PM
 */

package gui.action_data_ui;

/**
 *
 * @author rickster
 */
public class ActionData extends javax.swing.JFrame {

    /** Creates new form ActionData */
    public ActionData() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save_trainer_data_button = new javax.swing.JButton();
        action_class_label = new javax.swing.JLabel();
        open_inspector_button = new javax.swing.JButton();
        tag_options_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        action_data_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trainer Data");

        save_trainer_data_button.setFont(new java.awt.Font("Tahoma", 0, 18));
        save_trainer_data_button.setText("Save Trainer Data");

        action_class_label.setFont(new java.awt.Font("Tahoma", 0, 18));
        action_class_label.setForeground(new java.awt.Color(0, 0, 204));
        action_class_label.setText("Action Class");

        open_inspector_button.setFont(new java.awt.Font("Tahoma", 0, 18));
        open_inspector_button.setText("Open Inspector");

        tag_options_button.setFont(new java.awt.Font("Tahoma", 0, 18));
        tag_options_button.setText("Tag Options");

        action_data_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        action_data_panel.setLayout(new javax.swing.BoxLayout(action_data_panel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(action_data_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(action_class_label)
                            .addComponent(save_trainer_data_button, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tag_options_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(open_inspector_button, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(action_class_label)
                    .addComponent(open_inspector_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_trainer_data_button)
                    .addComponent(tag_options_button))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActionData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action_class_label;
    private javax.swing.JPanel action_data_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton open_inspector_button;
    private javax.swing.JButton save_trainer_data_button;
    private javax.swing.JButton tag_options_button;
    // End of variables declaration//GEN-END:variables

}
